[project]
name = "tobacco-chicago"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "altair>=5.4.1",
    "jupyter>=1.1.1",
    "numpy>=2.1.2",
    "pandas>=2.2.3",
]
